image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
    name: Rails server
    description: Rails application preview
  - port: 5432
    onOpen: ignore
    name: PostgreSQL
    description: PostgreSQL database

tasks:
  - name: Docker Compose
    init: |
      cd /workspace/rpggame
      docker-compose build
    command: |
      cd /workspace/rpggame
      docker-compose up

vscode:
  extensions:
    - rebornix.ruby
    - wingrunr21.vscode-ruby
    - castwide.solargraph
    - kaiwood.endwise 